import { PrismaClient, PropertyType, ListingType, PropertyStatus } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Clear existing data
  console.log('🗑️  Clearing existing data...')
  await prisma.property.deleteMany({})
  console.log('✅ Cleared all properties')

  // Create a sample user
  const hashedPassword = await bcrypt.hash('password123', 10)
  
  const user = await prisma.user.upsert({
    where: { email: 'demo@example.com' },
    update: {},
    create: {
      email: 'demo@example.com',
      name: 'Demo User',
      password: hashedPassword,
      phone: '+1 (555) 123-4567',
      role: 'AGENT',
    },
  })

  console.log('✅ Created demo user:', user.email)

  // Create sample properties
  const properties = [
    {
      title: 'Modern Downtown Apartment',
      description: 'Stunning modern apartment in the heart of downtown with amazing city views. Features include hardwood floors, stainless steel appliances, and in-unit washer/dryer.',
      price: 450000,
      address: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      latitude: 37.7749,
      longitude: -122.4194,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1200,
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/2251247/pexels-photo-2251247.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1648771/pexels-photo-1648771.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Hardwood Floors', 'City Views', 'In-Unit Laundry', 'Parking'],
      yearBuilt: 2020,
      virtualTourUrl: 'https://my.matterport.com/show/?m=example123',
      floorPlans: [
        'https://images.pexels.com/photos/8293778/pexels-photo-8293778.jpeg?auto=compress&cs=tinysrgb&w=1200',
        'https://images.pexels.com/photos/8293773/pexels-photo-8293773.jpeg?auto=compress&cs=tinysrgb&w=1200',
      ],
      userId: user.id,
    },
    {
      title: 'Spacious Family Home',
      description: 'Beautiful 4-bedroom family home in quiet suburban neighborhood. Large backyard, updated kitchen, and close to top-rated schools.',
      price: 750000,
      address: '456 Oak Avenue',
      city: 'San Jose',
      state: 'CA',
      zipCode: '95110',
      latitude: 37.3382,
      longitude: -121.8863,
      bedrooms: 4,
      bathrooms: 3,
      squareFeet: 2500,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Large Backyard', 'Updated Kitchen', 'Near Schools', '2-Car Garage'],
      yearBuilt: 2015,
      virtualTourUrl: 'https://my.matterport.com/show/?m=example456',
      floorPlans: [
        'https://images.pexels.com/photos/7031705/pexels-photo-7031705.jpeg?auto=compress&cs=tinysrgb&w=1200',
      ],
      userId: user.id,
    },
    {
      title: 'Luxury Condo with Bay Views',
      description: 'Incredible luxury condo with panoramic bay views. High-end finishes throughout, building amenities include pool, gym, and concierge.',
      price: 1200000,
      address: '789 Bay Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94133',
      latitude: 37.8044,
      longitude: -122.4100,
      bedrooms: 3,
      bathrooms: 2.5,
      squareFeet: 1800,
      propertyType: PropertyType.CONDO,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1648771/pexels-photo-1648771.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/2251247/pexels-photo-2251247.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Bay Views', 'Pool', 'Gym', 'Concierge', 'Parking'],
      yearBuilt: 2018,
      floorPlans: [
        'https://images.pexels.com/photos/8293778/pexels-photo-8293778.jpeg?auto=compress&cs=tinysrgb&w=1200',
      ],
      userId: user.id,
    },
    {
      title: 'Charming Studio for Rent',
      description: 'Cozy studio apartment perfect for young professionals. Walking distance to public transit, shops, and restaurants.',
      price: 2200,
      address: '321 Market Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
      latitude: 37.7749,
      longitude: -122.4194,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 550,
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.FOR_RENT,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1457847/pexels-photo-1457847.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Near Transit', 'Walkable', 'Pet Friendly'],
      yearBuilt: 2010,
      userId: user.id,
    },
    {
      title: 'Elegant Townhouse',
      description: 'Beautifully renovated townhouse with modern amenities and classic charm. Three levels of living space with private patio.',
      price: 850000,
      address: '555 Elm Street',
      city: 'Oakland',
      state: 'CA',
      zipCode: '94612',
      latitude: 37.8044,
      longitude: -122.2712,
      bedrooms: 3,
      bathrooms: 2.5,
      squareFeet: 2000,
      propertyType: PropertyType.TOWNHOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1546168/pexels-photo-1546168.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Private Patio', 'Renovated', 'Garage', 'Storage'],
      yearBuilt: 2005,
      userId: user.id,
    },
    {
      title: 'Waterfront Luxury Villa',
      description: 'Stunning waterfront villa with private dock and breathtaking sunset views. Custom-built with premium materials and smart home technology.',
      price: 2500000,
      address: '1200 Marina Boulevard',
      city: 'Sausalito',
      state: 'CA',
      zipCode: '94965',
      latitude: 37.8590,
      longitude: -122.4852,
      bedrooms: 5,
      bathrooms: 4.5,
      squareFeet: 4500,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Waterfront', 'Private Dock', 'Smart Home', 'Pool', 'Wine Cellar'],
      yearBuilt: 2021,
      userId: user.id,
    },
    {
      title: 'Cozy Cottage in Palo Alto',
      description: 'Charming cottage-style home with abundant natural light and beautiful garden. Perfect for first-time buyers or investors.',
      price: 1100000,
      address: '234 University Avenue',
      city: 'Palo Alto',
      state: 'CA',
      zipCode: '94301',
      latitude: 37.4419,
      longitude: -122.1430,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1600,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Garden', 'Natural Light', 'Hardwood Floors', 'Updated Kitchen'],
      yearBuilt: 1965,
      userId: user.id,
    },
    {
      title: 'Modern Loft in SOMA',
      description: 'Industrial-chic loft with exposed brick, high ceilings, and floor-to-ceiling windows. Designer finishes throughout.',
      price: 3500,
      address: '678 Brannan Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94107',
      latitude: 37.7799,
      longitude: -122.3988,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1400,
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.FOR_RENT,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/2227832/pexels-photo-2227832.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1648768/pexels-photo-1648768.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Exposed Brick', 'High Ceilings', 'Natural Light', 'In-Unit Laundry'],
      yearBuilt: 2019,
      userId: user.id,
    },
    {
      title: 'Victorian Home in Noe Valley',
      description: 'Classic San Francisco Victorian with original details, updated systems. Perfect blend of historic charm and modern convenience.',
      price: 1650000,
      address: '890 Sanchez Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94114',
      latitude: 37.7510,
      longitude: -122.4290,
      bedrooms: 4,
      bathrooms: 3,
      squareFeet: 2800,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Victorian Details', 'Updated Systems', 'Fireplace', 'Backyard'],
      yearBuilt: 1902,
      userId: user.id,
    },
    {
      title: 'Penthouse with Rooftop Terrace',
      description: 'Spectacular penthouse with private rooftop terrace and 360-degree city views. Top-of-the-line finishes and amenities.',
      price: 3200000,
      address: '100 Van Ness Avenue',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      latitude: 37.7796,
      longitude: -122.4193,
      bedrooms: 4,
      bathrooms: 3.5,
      squareFeet: 3200,
      propertyType: PropertyType.CONDO,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Rooftop Terrace', '360 Views', 'High-end Finishes', 'Concierge', 'Valet Parking'],
      yearBuilt: 2020,
      userId: user.id,
    },
    {
      title: 'Suburban Home with Pool',
      description: 'Spacious single-family home with resort-style pool and landscaped yard. Perfect for entertaining and family living.',
      price: 950000,
      address: '456 Maple Drive',
      city: 'Fremont',
      state: 'CA',
      zipCode: '94539',
      latitude: 37.5485,
      longitude: -121.9886,
      bedrooms: 5,
      bathrooms: 3,
      squareFeet: 3000,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/261146/pexels-photo-261146.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/221024/pexels-photo-221024.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Pool', 'Large Yard', '3-Car Garage', 'Updated Kitchen', 'Solar Panels'],
      yearBuilt: 2012,
      userId: user.id,
    },
    {
      title: 'Affordable Starter Condo',
      description: 'Well-maintained condo in convenient location. Great for first-time buyers or as investment property with rental potential.',
      price: 425000,
      address: '789 Mission Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
      latitude: 37.7833,
      longitude: -122.4167,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 750,
      propertyType: PropertyType.CONDO,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1457847/pexels-photo-1457847.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Near Transit', 'HOA Amenities', 'Storage Unit', 'Pet Friendly'],
      yearBuilt: 2008,
      userId: user.id,
    },
    {
      title: 'Luxe Apartment with City Views',
      description: 'High-rise luxury apartment with stunning city and bay views. Building features include pool, fitness center, and 24/7 concierge.',
      price: 4800,
      address: '301 Mission Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      latitude: 37.7911,
      longitude: -122.3966,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1350,
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.FOR_RENT,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/2251247/pexels-photo-2251247.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1648771/pexels-photo-1648771.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['City Views', 'Pool', 'Gym', 'Concierge', 'Parking Included'],
      yearBuilt: 2022,
      userId: user.id,
    },
    {
      title: 'Craftsman Bungalow',
      description: 'Lovingly maintained Craftsman-style bungalow with original built-ins and period details. Walk to shops and restaurants.',
      price: 890000,
      address: '567 Peralta Avenue',
      city: 'Berkeley',
      state: 'CA',
      zipCode: '94707',
      latitude: 37.8715,
      longitude: -122.2730,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1800,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Original Details', 'Built-ins', 'Hardwood Floors', 'Front Porch'],
      yearBuilt: 1922,
      userId: user.id,
    },
    {
      title: 'Contemporary Townhome',
      description: 'Brand new contemporary townhome with open floor plan and designer finishes. Energy-efficient with solar panels.',
      price: 780000,
      address: '432 Willow Street',
      city: 'Redwood City',
      state: 'CA',
      zipCode: '94063',
      latitude: 37.4852,
      longitude: -122.2364,
      bedrooms: 3,
      bathrooms: 2.5,
      squareFeet: 1900,
      propertyType: PropertyType.TOWNHOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Solar Panels', 'Open Floor Plan', 'New Construction', 'Smart Home', 'Rooftop Deck'],
      yearBuilt: 2024,
      userId: user.id,
    },
    {
      title: 'Mountain View Ranch House',
      description: 'Single-story ranch house on large lot with fruit trees and vegetable garden. Quiet neighborhood near tech companies.',
      price: 1350000,
      address: '890 Central Avenue',
      city: 'Mountain View',
      state: 'CA',
      zipCode: '94040',
      latitude: 37.3861,
      longitude: -122.0839,
      bedrooms: 4,
      bathrooms: 2,
      squareFeet: 2200,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/221024/pexels-photo-221024.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Large Lot', 'Fruit Trees', 'Single Story', 'Near Tech Companies'],
      yearBuilt: 1975,
      userId: user.id,
    },
    {
      title: 'Stylish Studio in Mission District',
      description: 'Trendy studio in the heart of Mission District. Walk to cafes, galleries, and nightlife. Perfect for urban lifestyle.',
      price: 2400,
      address: '234 Valencia Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
      latitude: 37.7658,
      longitude: -122.4214,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 500,
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.FOR_RENT,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Walkable', 'Near Transit', 'Trendy Area', 'Pet Friendly'],
      yearBuilt: 2016,
      userId: user.id,
    },
    {
      title: 'Executive Home in Los Altos',
      description: 'Prestigious executive home in sought-after Los Altos neighborhood. Premium finishes, gourmet kitchen, and resort-style backyard.',
      price: 3800000,
      address: '1234 Los Altos Drive',
      city: 'Los Altos',
      state: 'CA',
      zipCode: '94022',
      latitude: 37.3688,
      longitude: -122.1147,
      bedrooms: 6,
      bathrooms: 5.5,
      squareFeet: 5200,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/261146/pexels-photo-261146.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Pool', 'Gourmet Kitchen', 'Home Office', 'Wine Cellar', '4-Car Garage'],
      yearBuilt: 2019,
      userId: user.id,
    },
    {
      title: 'Family-Friendly Duplex',
      description: 'Great investment opportunity! Live in one unit and rent the other. Both units recently updated. Strong rental market.',
      price: 1200000,
      address: '678 Lincoln Avenue',
      city: 'Alameda',
      state: 'CA',
      zipCode: '94501',
      latitude: 37.7652,
      longitude: -122.2416,
      bedrooms: 6,
      bathrooms: 4,
      squareFeet: 3400,
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Duplex', 'Investment Opportunity', 'Updated Units', 'Separate Entrances'],
      yearBuilt: 1968,
      userId: user.id,
    },
    {
      title: 'Marina District Flat',
      description: 'Bright and airy flat in desirable Marina District. Near parks, waterfront, and restaurants. Deeded parking included.',
      price: 1450000,
      address: '2100 Lombard Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94123',
      latitude: 37.7999,
      longitude: -122.4397,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1650,
      propertyType: PropertyType.CONDO,
      listingType: ListingType.FOR_SALE,
      status: PropertyStatus.ACTIVE,
      images: [
        'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
        'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800',
      ],
      features: ['Near Waterfront', 'Deeded Parking', 'Natural Light', 'Near Parks'],
      yearBuilt: 1985,
      userId: user.id,
    },
  ]

  for (const propertyData of properties) {
    const property = await prisma.property.create({
      data: propertyData,
    })
    console.log('✅ Created property:', property.title)
  }

  console.log('🎉 Seeding completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
